spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: Subham@123

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081