spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/commentdb
    username: root
    password: Subham@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
server-url:
  defaultZone: http://localhost:8761/eureka
